#!/bin/sh

# if we do not have debconf, we just skip this
. /usr/share/debconf/confmodule || exit 0

db_version 2.0
db_capb
db_title Adduser

# For testing
#db_fset adduser/homedir-permission isdefault true

CUR_DIRMODE=`cat /etc/adduser.conf | sed -ne 's/^DIR_MODE=\(.*\)$/\1/p;'`
if [ -z "$CUR_DIRMODE" ]
then
	CUR_DIRMODE="0755" # this is addusers default
fi

if [ $CUR_DIRMODE = "0755" -o $CUR_DIRMODE = "755" ]
then
	db_set adduser/homedir-permission true
elif [ $CUR_DIRMODE = "0751" -o $CUR_DIRMODE = "751" ]
then
	db_set adduser/homedir-permission false
else
	CHANGED=1
fi

if [ -z "$CHANGED" ]
then
	db_unregister adduser/homedir-changed
	db_input medium adduser/homedir-permission
	db_go
else
	db_register adduser/homedir-permission adduser/homedir-changed
	db_set adduser/homedir-changed true
fi
